    --liquibase formatted sql

    --changeset vmarmuz:1
    CREATE TABLE IF NOT EXISTS user
    (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(64) NOT NULL,
        email VARCHAR(64) NOT NULL UNIQUE,
        password VARCHAR(200) NOT NULL
        );

    --changeset vmarmuz:2
    CREATE TABLE IF NOT EXISTS album
    (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at DATE NOT NULL
        user_id INT REFERENCES user (id) ON DELETE CASCADE
        );

    --changeset vmarmuz:3
    CREATE TABLE IF NOT EXISTS page
    (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        description text NOT NULL,
        color VARCHAR(60),
        template_page VARCHAR(60),
        tag_people VARCHAR(200),
        tag_place VARCHAR(200),
        animation VARCHAR(60),
        album_id INT REFERENCES album (id) ON DELETE CASCADE
        );

    --changeset vmarmuz:4
    CREATE TABLE IF NOT EXISTS cover
    (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        description VARCHAR(100),
        album_id INT UNIQUE REFERENCES album (id)ON DELETE CASCADE
        );

    --changeset vmarmuz:5
    CREATE TABLE IF NOT EXISTS Image
    (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        link VARCHAR(200) NOT NULL ,
        cover_id INT UNIQUE REFERENCES cover (id),
        page_id INT REFERENCES page (id)
        );
