openapi: 3.0.3
info:
  description: This specification is intended to describe the functionality of the
    photo album application (Album and image part)
  title: Photo album OpenAPI specification
  version: 1.0.11
servers:
  - description: Dev server
    url: http://localhost:8080
paths:
  /albums:
    post:
      summary: Method for created album
      tags:
        - AlbumController
      operationId: createAlbum
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlbumModel'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlbumModel'
        '400':
          description: something wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'

  /albums/{userId}:
    get:
      tags:
        - AlbumController
      summary: Find album by userId
      description: Find album by userId
      operationId: getAlbumByUserId
      parameters:
        - name: userId
          in: path
          description: userId , which need to find an album
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AlbumModel'
        '404':
          description: not found
        '500':
          description: something wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'

  /albums/{albumId}:
    get:
      tags:
        - AlbumController
      summary: Find album by ID
      description: Find album by ID
      operationId: getAlbum
      parameters:
        - name: albumId
          in: path
          description: id , which need to find page
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlbumModel'
        '404':
          description: Not found
        '400':
          description: something wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'

    put:
      summary: Update album
      tags:
        - AlbumController
      description: Method for update album
      operationId: updateAlbum
      parameters:
        - name: albumId
          in: path
          description: id that need to update album
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent user in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlbumModel'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlbumModel'
        '400':
          description: something wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'

    delete:
      tags:
        - AlbumController
      summary: Delete album by albumId
      description: Method for delete album
      operationId: deleteAlbum
      parameters:
        - name: albumId
          in: path
          description: ID of the cover that needs to be deleted
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema: { }
        '400':
          description: something wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'

  /images/{name}:
    get:
      tags:
        - ImageController
      summary: Find image by name
      description: Find image by name
      operationId: downloadImage
      parameters:
        - name: name
          in: path
          description: name , which need to find image
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  type: string
                  format: byte
        '400':
          description: something wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'

  /images:
    post:
      summary: Method for created image
      tags:
        - ImageController
      operationId: uploadImage
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageModel'
        '400':
          description: something wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'

  /images/{id}:
    delete:
      tags:
        - ImageController
      summary: Delete image by ID
      description: Method for delete image
      operationId: deleteImage
      parameters:
        - name: id
          in: path
          description: ID for delete image
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema: { }
        '400':
          description: something wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'

components:
  schemas:
    AlbumModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        albumDescription:
          type: string
          example: some words about page
        color:
          type: string
          example: red
        templatePage:
          type: string
          example: Horizontal image and text field below
        tagPeople:
          type: string
          example: Andrew,Egor
        tagPlace:
          type: string
          example: Germany,Berlin
        animation:
          type: string
          example: slide
        coverDescription:
          type: string
          example: place description
        images:
          type: array
          items:
            $ref: '#/components/schemas/ImageModel'

    ImageModel:
      type: object
      required:
        - link
      properties:
        id:
          type: integer
          format: int64
        link:
          type: string
          example: photo link
        name:
          type: string
          example: name
        type:
          type: string
          example: type
        albumId:
          type: integer
          format: int64

    ApplicationError:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string