openapi: 3.0.3
info:
  description: This specification is intended to describe the functionality of the
    photo album application (User's part)
  title: Photo album OpenAPI specification
  version: 1.0.11
servers:
  - description: Dev server
    url: http://localhost:8080
paths:
  /users/login:
    post:
      summary: Method for user authorization
      tags:
        - AuthController
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: something wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'

  /users/refresh-token:
    post:
      summary: Method for refresh token
      tags:
        - AuthController
      description: refresh user's auth
      operationId: refresh
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshToken'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: something wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'

  /users/forgot-password:
    post:
      summary: Forgot password
      tags:
        - ForgotPasswordController
      description: after this method user should check his email
      operationId: forgotPassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPassword'
      responses:
        '200':
          description: successful operation of creation new password
        '400':
          description: something wrong with password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'
  /users/confirm-account:
    post:
      summary: Confirmation of user's account by email controller
      tags:
        - UserConfirmationMailController
      description: method for sending confirmation email to user's mail
      operationId: confirmUserAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserModel'
      responses:
        '200':
          description: success sending mail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserModel'

        '500':
          description: something went wrong with user's email
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'
  /users/verify:
    get:
      summary: User verifies his account
      tags:
        - UserConfirmationMailController
      description: method verify account
      operationId: verifyAccount
      parameters:
        - name: token
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: account verified within success
          content:
            application/json:
              schema:
                type: string
            text/html:
              schema:
                type: string

        '500':
          description: verifying went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'

  /users/reset-password:
    post:
      summary: Reset user's password
      tags:
        - ForgotPasswordController
      description: Method for reset user's password
      operationId: resetPassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPassword'
      responses:
        default:
          description: successful operation
        '400':
          description: something wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'
  /users/upgrade-password:
    post:
      summary: Method change old password
      tags:
        - ForgotPasswordController
      description: changing old password of user
      operationId: changePassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePasswordModel'
      responses:
        '200':
          description: password has been change
        '500':
          description: something went wrong with input form
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'

  /users/{userId}:
    get:
      tags:
        - UserController
      summary: Find user by userId
      description: Find user by userId
      operationId: getUser
      parameters:
        - name: userId
          in: path
          description: userId for finding user
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: user found successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserModel'
        '404':
          description: not found
        '500':
          description: something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'
    put:
      summary: Update password
      tags:
        - UserController
      description: Method for update password
      operationId: updatePassword
      parameters:
        - name: userId
          in: path
          description: userId to update password
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update an existent user in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePassword'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
        '400':
          description: something wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'
    post:
      summary: Add profile photo
      tags:
        - UserController
      description: Method for add user's photo
      operationId: addProfilePhoto
      parameters:
        - name: userId
          in: path
          description: userId to add photo
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        '500':
          description: something wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'

    delete:
      tags:
        - UserController
      summary: Delete user userId
      description: Method for delete user
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          description: ID for delete user
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
        '400':
          description: something wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'
    patch:
      summary: Method to update user's email
      tags:
        - UserController
      description: update email
      operationId: updateExistsEmail
      parameters:
        - name: userId
          in: path
          description: usr id for checking email
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserModel'
      responses:
        '200':
          description: successfully update email
        '400':
          description: something went wrong..
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'

components:
  schemas:
    UserModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: theUser
          #comment email should be new value
        email:
          type: string
          example: egor@email.com
        password:
          type: string
          example: 2uffu4fuo

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          example: egor@email.com
        password:
          type: string
          example: MyNew_pass

    ForgotPassword:
      type: object
      properties:
        email:
          type: string
          example: egor@email.com
        new_password:
          type: string
          example: 3274ert

    UpdatePassword:
      type: object
      properties:
        token:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        name:
          type: string
        token:
          $ref: '#/components/schemas/Token'

    Token:
      type: object
      properties:
        accessToken:
          type: string
        expirationIn:
          type: integer
          format: int64
        refreshToken:
          type: string

    RefreshToken:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        refreshToken:
          type: string

    UpdatePasswordModel:
      type: object
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string

    AlbumModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        albumDescription:
          type: string
          example: some words about page
        albumName:
          type: string
          example: name of album
        color:
          type: string
          example: red
        templatePage:
          type: string
          example: Horizontal image and text field below
        tagPeople:
          type: string
          example: Andrew,Egor
        tagPlace:
          type: string
          example: Germany,Berlin
        animation:
          type: string
          example: slide
        coverDescription:
          type: string
          example: place description
        images:
          type: array
          items:
            $ref: '#/components/schemas/ImageModel'

    ImageModel:
      type: object
      required:
        - link
      properties:
        id:
          type: integer
          format: int64
        link:
          type: string
          example: photo link
        name:
          type: string
          example: name
        type:
          type: string
          example: type
        albumId:
          type: integer
          format: int64

    ApplicationError:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string