--liquibase formatted sql

--changeset vmarmuz:1
CREATE TABLE IF NOT EXISTS users
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    email VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    confirmation_reset_token VARCHAR(250) NULL,
    reset_password_token VARCHAR(250) NULL,
    role VARCHAR(45) NOT NULL
    );

--changeset vmarmuz:2
CREATE TABLE IF NOT EXISTS album
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cover_description VARCHAR(100) NOT NULL,
    album_description text NOT NULL,
    album_name text not null,
    color VARCHAR(60) NOT NULL,
    template_page VARCHAR(60) NOT NULL,
    tag_people VARCHAR(200) NOT NULL,
    tag_place VARCHAR(200) NOT NULL,
    animation VARCHAR(60) NOT NULL,
    album_name varchar(60) not null,
    user_id INT REFERENCES users (id) ON DELETE CASCADE
    );

--changeset vmarmuz:3
CREATE TABLE IF NOT EXISTS image
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link VARCHAR(200) NOT NULL ,
    description text ,
    name VARCHAR(150) UNIQUE NOT NULL ,
    type VARCHAR(150) NOT NULL ,
    album_id INT UNIQUE REFERENCES album (id)
    );