--liquibase formatted sql

--changeset vmarmuz:1
CREATE TABLE IF NOT EXISTS users
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    email VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    confirmation_reset_token VARCHAR(250) NULL,
    role VARCHAR(45) NOT NULL
    );

--changeset vmarmuz:2
CREATE TABLE IF NOT EXISTS album
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users (id) ON DELETE CASCADE
    );

--changeset vmarmuz:3
CREATE TABLE IF NOT EXISTS page
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description text NOT NULL,
    color VARCHAR(60) NOT NULL,
    template_page VARCHAR(60) NOT NULL,
    tag_people VARCHAR(200) NOT NULL,
    tag_place VARCHAR(200) NOT NULL,
    animation VARCHAR(60) NOT NULL,
    album_id INT REFERENCES album (id) ON DELETE CASCADE
    );

--changeset vmarmuz:4
CREATE TABLE IF NOT EXISTS cover
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(100) NOT NULL,
    album_id INT UNIQUE REFERENCES album (id)ON DELETE CASCADE
    );

--changeset vmarmuz:5
CREATE TABLE IF NOT EXISTS image
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link VARCHAR(200) NOT NULL ,
    cover_id INT UNIQUE REFERENCES cover (id),
    page_id INT REFERENCES page (id)
    );